# Generated by Django 5.0.1 on 2026-03-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success/Promotion'), ('warning', 'Warning'), ('danger', 'Important')], default='info', max_length=20)),
                ('link_text', models.CharField(blank=True, help_text='e.g., "View Offer"', max_length=50)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_on_all_pages', models.BooleanField(default=False, help_text='Show as top banner on all pages')),
                ('start_date', models.DateTimeField(blank=True, help_text='Leave empty for immediate', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Leave empty for no end', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher = appears first')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Can users close it?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading (e.g., "Learn Without Limits")', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle or description')),
                ('background_image', models.ImageField(help_text='Recommended size: 1920x800px', upload_to='hero_slides/')),
                ('gradient_color', models.CharField(choices=[('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('red', 'Red')], default='purple', max_length=20)),
                ('button_text', models.CharField(default='Explore Courses', max_length=50)),
                ('button_url', models.CharField(default='/courses/', max_length=200)),
                ('show_secondary_button', models.BooleanField(default=True, help_text='Show "Get Started" button')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (0, 1, 2...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order'],
            },
        ),
    ]
