# Generated by Django 5.0.1 on 2026-03-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_heroslide_gradient_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='gradient_color',
            field=models.CharField(choices=[('none', 'No Gradient (Image Only)'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('blue', 'Blue'), ('red', 'Red')], default='purple', max_length=20),
        ),
    ]
